/*
Leap Workflows API

The Leap Workflows API allows developers to run workflows, fetch workflow runs, and provide other utility functions related to workflow runs. Please use the X-Api-Key for authenticated requests.

The version of the OpenAPI document: 1.0
Contact: help@tryleap.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  WorkflowRunsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LeapCustom } from "./client-custom";

export class Leap extends LeapCustom {
  readonly workflowRuns: WorkflowRunsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.workflowRuns = new WorkflowRunsApi(configuration);
  }

}
