/*
Leap Workflows API

The Leap Workflows API allows developers to run workflows, fetch workflow runs, and provide other utility functions related to workflow runs. Please use the X-Api-Key for authenticated requests.

The version of the OpenAPI document: 1.0
Contact: help@tryleap.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BulkRunSchema
 */
export interface BulkRunSchema {
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'version_id': string;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'status': BulkRunSchemaStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'workflow_id': string;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'input_csv_url': string;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'output_csv_url': string | null;
    /**
     * 
     * @type {string}
     * @memberof BulkRunSchema
     */
    'error': string | null;
    /**
     * 
     * @type {number}
     * @memberof BulkRunSchema
     */
    'row_count': number;
}

type BulkRunSchemaStatusEnum = 'completed' | 'running' | 'failed' | 'queued' | 'cancelled'


