/*
Leap Workflows API

The Leap Workflows API allows developers to run workflows, fetch workflow runs, and provide other utility functions related to workflow runs. Please use the X-Api-Key for authenticated requests.

The version of the OpenAPI document: 1.0
Contact: help@tryleap.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RunBulkWorkflowSchema
 */
export interface RunBulkWorkflowSchema {
    /**
     * The ID of the workflow to be run in bulk.
     * @type {string}
     * @memberof RunBulkWorkflowSchema
     */
    'workflow_id': string;
    /**
     * A CSV file containing the input data for the bulk run. Each row should contain the input data for a single run.
     * @type {string}
     * @memberof RunBulkWorkflowSchema
     */
    'input_csv_url': string;
    /**
     * The URL to which the bulk run results should be sent to on completion.
     * @type {string}
     * @memberof RunBulkWorkflowSchema
     */
    'webhook_url'?: string;
}

