/*
Leap Workflows API

The Leap Workflows API allows developers to run workflows, fetch workflow runs, and provide other utility functions related to workflow runs. Please use the X-Api-Key for authenticated requests.

The version of the OpenAPI document: 1.0
Contact: help@tryleap.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkflowRunSchema
 */
export interface WorkflowRunSchema {
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'version_id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'status': WorkflowRunSchemaStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'started_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'ended_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'workflow_id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunSchema
     */
    'error': string | null;
    /**
     * 
     * @type {object}
     * @memberof WorkflowRunSchema
     */
    'input': object | null;
    /**
     * 
     * @type {object}
     * @memberof WorkflowRunSchema
     */
    'output': object | null;
}

type WorkflowRunSchemaStatusEnum = 'completed' | 'running' | 'failed' | 'queued' | 'cancelled'


