/*
Leap Workflows API

The Leap Workflows API allows developers to run workflows, fetch workflow runs, and provide other utility functions related to workflow runs. Please use the X-Api-Key for authenticated requests.

The version of the OpenAPI document: 1.0
Contact: help@tryleap.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


/**
 * 
 * @export
 * @interface WorkflowRunEntity
 */
export interface WorkflowRunEntity {
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'version_id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'status': WorkflowRunEntityStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'started_at': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'ended_at': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'workflow_id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRunEntity
     */
    'error': string;
    /**
     * 
     * @type {object}
     * @memberof WorkflowRunEntity
     */
    'input': object;
    /**
     * 
     * @type {object}
     * @memberof WorkflowRunEntity
     */
    'output': object;
}

type WorkflowRunEntityStatusEnum = 'completed' | 'running' | 'failed'


